//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MBISDKTEST.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MBI_API_TEST_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_MBI_SDK_TEST_DIALOG         130
#define IDD_MBISDK_TEST_DIALOG          130
#define IDC_BTN_LOAD_FILE               1000
#define IDC_BTN_NUM_FRAMES              1001
#define IDC_BTN_MAX_SCANS               1002
#define IDC_BTN_CALIBRATION             1003
#define IDC_BTN_TOF_ERROR               1004
#define IDC_BTN_INDEX_MICRO             1005
#define IDC_BTN_INDEX_MZ                1006
#define IDC_BTN_MICRO_MZ                1007
#define IDC_BTN_MZ_MICRO                1008
#define IDC_BTN_MZ_INDEX                1009
#define IDC_BTN_SLOPE                   1010
#define IDC_BTN_INTERCEPT               1011
#define IDC_BTN_MAX_POINTS              1012
#define IDC_BTN_TIME_1_5                1013
#define IDC_STATIC_1                    1014
#define IDC_STATIC_FILENAME             1014
#define IDC_STATIC_2                    1015
#define IDC_STATIC_3                    1016
#define IDC_STATIC_4                    1017
#define IDC_STATIC_5                    1018
#define IDC_STATIC_6                    1019
#define IDC_STATIC_7                    1020
#define IDC_STATIC_8                    1021
#define IDC_STATIC_9                    1022
#define IDC_STATIC_10                   1023
#define IDC_STATIC_11                   1024
#define IDC_STATIC_12                   1025
#define IDC_STATIC_13                   1026
#define IDC_STATIC_14                   1027
#define IDC_BTN_AUTOMATE                1029
#define IDC_STATIC_15                   1034
#define IDC_STATIC_16                   1035
#define IDC_STATIC_17                   1036
#define IDC_STATIC_18                   1037
#define IDC_BTN_SCAN_MZ_INDEX_SPARSE    1038
#define IDC_BTN_SCAN_MZ_INDEX_DENSE     1039
#define IDC_BTN_SCAN_TOF_INDEX_SPARSE   1040
#define IDC_BTN_SCAN_TOF_INDEX_DENSE    1041
#define IDC_BTN_IS_FRAG_DATA            1042
#define IDC_STATIC_19                   1043
#define IDC_BTN_LOAD_FRAMES             1044
#define IDC_STATIC_20                   1045
#define IDC_BTN_CCS                     1046
#define IDC_STATIC_ATTIC_DATA           1046
#define IDC_STATIC_CCS_OUTPUT           1047
#define IDC_STATIC_RTTIC_DATA           1047
#define IDC_STATIC_PICTURE              1048
#define IDC_STATIC_INDEX_COUNT_DATA     1048
#define IDC_STATIC_DISPLAY_LOWEST       1049
#define IDC_STATIC_INDEX_POSITION_DATA  1049
#define IDC_STATIC_DISPLAY_HIGHEST      1050
#define IDC_STATIC_DATA_COUNT_DATA      1050
#define IDC_STATIC_DATA_POSITION_DATA   1051
#define IDC_STATIC_SCAN_HIGH            1052
#define IDC_STATIC_SCAN_LOW             1053
#define IDC_STATIC_FRAME_NUM            1054
#define IDC_BTN_DISPLAY_FRAME_DOWN      1055
#define IDC_BTN_DISPLAY_FRAME_UP        1056
#define IDC_STATIC_FRAME_NUM3           1056
#define IDC_STATIC_END_SCAN_NUM         1056
#define IDC_BTN_CCS_CALC                1058
#define IDC_STATIC_FILE_NAME            1059
#define IDC_STATIC_VERSION              1060
#define IDC_STATIC_CGV                  1061
#define IDC_STATIC_CGV_INDEX            1062
#define IDC_BTN_SMP_COM                 1063
#define IDC_STATIC_SMP_CON              1064
#define IDC_STATIC_LEFT_CON             1065
#define IDC_STATIC_RIGHT_CON            1066
#define IDC_STATIC_LEFT_INDEX           1067
#define IDC_STATIC_CENTER_INDEX         1068
#define IDC_STATIC_RIGHT_INDEX          1069
#define IDC_BUTTON_QUAD                 1070
#define IDC_STATIC_A_COEFF              1071
#define IDC_STATIC_B_COEFF              1072
#define IDC_STATIC_C_COEFF              1073
#define IDC_BTN_CUBIC_TEST              1074
#define IDC_STATIC_D_COEFF              1075
#define IDC_BTN_LFT_SCAN                1077
#define IDC_BTN_RGH_SCAN                1078
#define IDC_BTN_MZ_DATA                 1079
#define IDC_BTN_FMS_TEST                1080
#define IDC_STATIC_FRAME_METHOD_STATE   1081
#define IDC_BTN_SCANS_GATES             1083
#define IDC_SPIN1_FRAME_NUM             1089
#define IDC_STATIC_START_SCAN_NUM       1090
#define IDC_STATIC_SCAN_END_NUM         1091
#define IDC_STATIC_SCAN_END_NUM_TEXT    1091
#define IDC_SPIN_START_SCAN_NUM         1093
#define IDC_SPIN_END_SCAN_NUM           1094
#define IDC_EDIT_FRAME_NUM              1095
#define IDC_EDIT_START_SCAN_NUM         1096
#define IDC_EDIT_END_SCAN_NUM           1097
#define IDC_COMBO_START_SCAN            1099
#define IDC_COMBO_END_SCAN              1101
#define IDC_COMBO_FRAME                 1102
#define IDC_RADIO_INTENSITY             1103
#define IDC_RADIO_MZ                    1104
#define IDC_BTN_TRIM                    1105
#define IDC_EDIT_TRIM                   1106
#define IDC_STATIC_45                   1107
#define IDC_BTN_STITCH                  1108
#define IDC_STATIC_46                   1109
#define IDC_BTN_CCS_READ                1110
#define IDC_BTN_COMPARE                 1111
#define IDC_STATIC_COMPARE              1112
#define IDC_BUTTON_TEST_NEW             1113
#define IDC_BUTTON_PRIME                1114
#define IDC_BUTTON_STITCH_NINE          1115
#define IDC_BUTTON_SHOW_ATTIC           1116
#define IDC_BUTTON_RT_TIC               1117
#define IDC_BUTTON_INDEX_COUNT          1118
#define IDC_BUTTON_INDEX_POSITION       1119
#define IDC_BUTTON_DATA_COUNT           1120
#define IDC_BUTTON_DATA_POSITION        1121

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
